name: linting

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-and-package
      - name: Check style against standards using prospector
        run: prospector
      - name: Check import order
        run: isort --check-only dianna --diff
