name: markdown-link-check-cron

on:
    schedule:
    # See https://codebeautify.org/crontab-format for cron format
    - cron:  '0 0 1 * *'
jobs:

  markdown-link-check:
    name: Check markdown links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/mlc-config.json'
